name: CI

on:
  workflow_dispatch:

  push:
    branches:
      - 'feature/*'
      - master

  pull_request:
    branches:
      - master

jobs:
  plan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.9.5"

    - name: Build Lambda zip file
      working-directory: ./collect
      run: |
        pip install --platform manylinux2014_x86_64 --only-binary=:all: --target=package/ -r requirements.txt
        cp collect.py package/
        cd package
        zip -r ../collect.zip .

    - name: Terraform Init
      working-directory: ./infrastructure
      run: terraform init -backend-config="bucket=garmin-tf-state" -backend-config="key=terraform/state.tfstate" -backend-config="region=eu-west-3"
    
    - name: Terraform Plan
      working-directory: ./infrastructure
      run: terraform plan -out=plan.out

    - name: Manual Approval
      run: echo "Waiting for manual approval..."
      if: ${{ github.event_name == 'workflow_dispatch' }}

    - name: Terraform Apply
      working-directory: ./infrastructure
      run: terraform apply plan.out
      if: ${{ (github.event_name == 'workflow_dispatch') || (github.event_name == 'push' && github.ref == 'refs/heads/master') }}